spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authDB
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: AUTHN-AUTHZ-SERVICE
  security:
    user:
      name: admin
      password: admin@123
server:
  port: 9001
  servlet:
    context-path: /api/v1
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /api-docs-ui
  packagesToScan: com.sivasankar
  pathsToMatch: /customers/**
---
## Self-defined properties
organization: Marlabs LLC

customer:
 id: CU0001
 code: ABC-0001
 name: ABC
 projectId: 101, 102, 103